services:
  - type: web
    name: weather-app-backend
    env: node
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: WEATHER_API_KEY
        sync: false
      - key: API_NINJA_KEY
        sync: false
    healthCheckPath: /health